algoritmo "semnome"
// Função :
// Autor :
// Data : 04/03/2015
// Seção de Declarações 
var
i:inteiro
inicio
// Seção de Comandos 
repita
escreval("Escreva a idade do jogador")
leia(i)
se (i >=5) e (i <=10) entao
escreval("O jogador é Infantil")
 senao
      se (i >=11) e (i <=17) entao
      escreval("O jogador é Juvenil")
      senao
           se i>=18 entao
           escreval("O jogador é Adulto")
fimse
fimse
fimse
ate i=0
fimalgoritmo
