algoritmo "semnome"
// Função :
// Autor :
// Data : 27/02/2015
// Seção de Declarações 
var
vt:real
i:inteiro
inicio
// Seção de Comandos 
escreval("Insira o valor total do produto")
leia(vt)
i <- 1
enquanto i<=500000000000 faca
escreval("====================================================")
escreval("Se voce parcelar ",vt,"R$ em :",i," vezes sem juros:")
escreval("                       O valor da parcela será:",vt/i)
i <- i+1
fimenquanto
fimalgoritmo
