algoritmo "semnome"
// Função :
// Autor :
// Data : 25/02/2015
// Seção de Declarações
var
A:vetor[1..10] de inteiro
B:vetor[1..10] de inteiro
x:inteiro

inicio
// Seção de Comandos 
x <- 1
para X de 1 ate 10 faca
escreval("digite A[",x,"]")
leia(A[X])
x <- x + 1
fimpara
x <- 1
para X de 1 ate 10 faca
escreval("digite B[",x,"]")
leia(B[X])
x <- x + 1
fimpara
x <- 1
para x de 1 ate 10 faca
escreval ("O valor de A[1] + B[1] é igual a:", (A[x])+(B[x]))
x <- x + 1
fimpara



fimalgoritmo
