Algoritmo "Nome Sexo e idade"
// Disciplina  : [Lógica de Programação]
// Professor(a): Gelton Cruz
// Descrição   : Ler nome e sexo e idade.
// Autor(a)    : Júlio Magalhães
// Data atual  : 15/09/2015
var
nome, sexo:caractere
idade:inteiro
Inicio
escreval("Digite seu nome")
leia(nome)
escreval("Digite seu sexo")
leia(sexo)
escreval("Digite sua idade")
leia(idade)
escreval("Nome: ",nome," Sexo: ",sexo," Idade: ",idade)
Fimalgoritmo